// styles.js — extracted from App.js so App.js fits under the mobile paste limit.
// Holds SH (request-sheet styles) and S_ (main app styles).
import { StyleSheet } from 'react-native';
import { C, S, R, T, E, M, Z, shadow, shadowSm, MONO } from './theme';

export const SH = StyleSheet.create({
  host: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'flex-end' },
  kav: { justifyContent: 'flex-end' },
  backdrop: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(15,15,20,0.32)' },
  sheet: { backgroundColor: 'rgba(251,251,249,0.97)', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingTop: 6, shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 26, shadowOffset: { width: 0, height: -8 }, elevation: 24 },
  grab: { width: 40, height: 5, borderRadius: 3, backgroundColor: C.line2, alignSelf: 'center', marginBottom: 6 },
  progressTrack: { height: 3, borderRadius: 2, backgroundColor: C.line2, marginBottom: 12, overflow: 'hidden' },
  progressFill: { height: 3, borderRadius: 2, backgroundColor: C.indigo },
  useLoc: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.indigoSoft, borderRadius: R.lg, paddingVertical: 15, paddingHorizontal: 16, marginTop: 4 },
  useLocPin: { fontSize: 18, color: C.indigo },
  useLocT: { fontSize: 15, fontWeight: '700', color: C.indigo, flex: 1 },
  useLocSub: { fontSize: 12, color: C.indigo, opacity: 0.7 },
  orType: { fontSize: 12, color: C.mute, textAlign: 'center', marginVertical: 12 },
  header: { paddingHorizontal: 20, paddingTop: 4, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: C.line },
  q: { fontFamily: MONO, fontSize: 18, fontWeight: '800', color: C.ink, letterSpacing: 0.2 },
  hint: { fontSize: 12, color: C.mute, marginBottom: 10, marginTop: 4 },
  opt: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: R.md, paddingVertical: 15, paddingHorizontal: 16, marginTop: 9 },
  optOn: { borderColor: C.indigo, backgroundColor: 'rgba(61,43,255,0.05)' },
  optT: { fontSize: 16, fontWeight: '600', color: C.ink },
  optTOn: { color: C.indigo },
  optArrow: { fontSize: 20, color: C.mute2 },
  optTick: { color: C.indigo, fontSize: 15, fontWeight: '800' },
  wrapChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  groupHead: { fontSize: 11, fontWeight: '800', letterSpacing: 0.4, textTransform: 'uppercase', marginBottom: 2 },
  door: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: C.panel, borderRadius: R.lg, paddingVertical: 16, paddingHorizontal: 16, marginTop: 10, ...E.sm },
  doorBar: { width: 4, alignSelf: 'stretch', borderRadius: 4 },
  doorLabel: { fontSize: 17, fontWeight: '800', color: C.ink, letterSpacing: -0.3 },
  doorSub: { fontSize: 12.5, color: C.mute, marginTop: 2 },
  doorDot: { width: 8, height: 8, borderRadius: 4 },
  pick: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 22, paddingVertical: 11, paddingHorizontal: 16 },
  pickT: { fontSize: 14, fontWeight: '600', color: C.ink },
  itemChip: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: 'rgba(61,43,255,0.06)', borderRadius: 10, paddingVertical: 9, paddingHorizontal: 12, marginBottom: 6 },
  itemChipT: { fontFamily: MONO, fontSize: 12.5, fontWeight: '700', color: C.indigo },
  itemChipX: { color: C.mute, fontSize: 13 },
  answered: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: C.line, marginBottom: 4 },
  answeredLabel: { fontFamily: MONO, fontSize: 10, color: C.mute },
  answeredValue: { flex: 1, fontSize: 13, color: C.ink, fontWeight: '600' },
  answeredEdit: { fontSize: 11, color: C.indigo },
  rateRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 14 },
  rStep: { width: 42, height: 42, borderRadius: 12, backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  rStepT: { fontSize: 20, color: C.ink, fontWeight: '600', lineHeight: 24 },
  rVal: { fontFamily: MONO, fontSize: 18, fontWeight: '800', color: C.ink, minWidth: 92, textAlign: 'center' },
  qtyBox: { flexDirection: 'row', alignItems: 'center', gap: 8, marginLeft: 'auto', backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 },
  qtyVal: { fontFamily: MONO, fontSize: 13, fontWeight: '700', color: C.ink, minWidth: 26, textAlign: 'center' },
  twoBtn: { flexDirection: 'row', gap: 10, marginTop: 20 },
  ghost: { flex: 1, borderWidth: 1.5, borderColor: C.line, borderRadius: R.md, paddingVertical: 14, alignItems: 'center' },
  ghostT: { fontFamily: MONO, fontSize: 13, fontWeight: '700', color: C.ink },
  next: { flex: 1, backgroundColor: C.indigo, borderRadius: R.md, paddingVertical: 14, alignItems: 'center' },
  nextT: { fontFamily: MONO, fontSize: 13, fontWeight: '800', color: '#fff', letterSpacing: 0.3 },
  reviewCard: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: R.md, padding: 14, marginTop: 12 },
  reviewRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  reviewName: { fontSize: 14, fontWeight: '700', color: C.ink },
  reviewRate: { fontFamily: MONO, fontSize: 13, color: C.ink },
  reviewMeta: { fontSize: 12.5, color: C.mute },
  reviewDiv: { height: 1, backgroundColor: C.line, marginVertical: 8 },
  send: { backgroundColor: C.ink, borderRadius: R.md, paddingVertical: 17, alignItems: 'center', marginTop: 16 },
  sendT: { fontFamily: MONO, fontSize: 15, fontWeight: '800', color: '#fff', letterSpacing: 0.3 },
  back: { fontFamily: MONO, fontSize: 12, color: C.mute },
  sentCheck: { width: 56, height: 56, borderRadius: 28, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center', marginBottom: 14 },
  sentCheckT: { color: '#fff', fontSize: 28, fontWeight: '800', lineHeight: 32 },
  sentT: { fontFamily: MONO, fontSize: 17, fontWeight: '800', color: C.ink },
  sentSub: { fontSize: 13, color: C.mute, marginTop: 4 },
  err: { color: C.red, fontSize: 12.5, marginTop: 10 },
  optionalLabel: { fontSize: 13, fontWeight: '800', color: C.ink, marginTop: 16, marginBottom: 7 },
  optionalHint: { fontSize: 12, fontWeight: '500', color: C.mute },
  optionalInput: { backgroundColor: C.panel, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15, color: C.ink, marginBottom: 10, borderWidth: 1, borderColor: C.line, shadowColor: '#000', shadowOpacity: 0.03, shadowRadius: 4, shadowOffset: { width: 0, height: 1 } },
  dayChip: { backgroundColor: C.canvas, borderRadius: 999, paddingHorizontal: 15, paddingVertical: 10, borderWidth: 1, borderColor: C.line },
  dayChipOn: { backgroundColor: C.indigo, borderColor: C.indigo },
  dayChipT: { fontSize: 13.5, fontWeight: '700', color: C.ink },
  dayChipTOn: { color: '#fff' },
});

export const S_ = StyleSheet.create({
  fill: { flex: 1, backgroundColor: C.canvas },
  homeLayer: { ...StyleSheet.absoluteFillObject },
  // Fully remove the inactive home from the render tree (not just opacity:0) — with full-bleed
  // maps, two live WebView maps compositing at once caused jank. display:none stops the hidden
  // map from rendering; the component stays mounted so switching sides is still instant.
  homeHidden: { display: 'none' },
  rateScrim: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', paddingHorizontal: 28 },
  rateCard: { backgroundColor: C.panel, borderRadius: 22, padding: 24 },
  rateTitle: { fontSize: 19, fontWeight: '800', color: C.ink, letterSpacing: -0.3 },
  rateSub: { fontSize: 13, color: C.mute, marginTop: 6, lineHeight: 18 },
  rateStars: { flexDirection: 'row', justifyContent: 'center', gap: 6, marginVertical: 20 },
  rateStarBtn: { padding: 4 },
  rateStar: { fontSize: 40, color: '#D8D8D4' },
  rateStarOn: { color: '#F5A623' },
  rateInput: { backgroundColor: C.canvas, borderRadius: 12, padding: 14, fontSize: 14, color: C.ink, minHeight: 64, textAlignVertical: 'top' },
  rateErr: { color: C.red, fontSize: 12.5, marginTop: 10 },
  rateSubmit: { backgroundColor: C.indigo, borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 16 },
  rateSubmitT: { color: '#fff', fontSize: 15, fontWeight: '800' },
  rateSkip: { color: C.mute, fontSize: 13.5, textAlign: 'center', fontWeight: '600' },
  rateThanks: { fontSize: 17, fontWeight: '800', color: C.green },
  // "good unit" tags + re-hire toggle inside the rating card
  rateTagWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
  rateTag: { borderWidth: 1.5, borderColor: C.line, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  rateTagOn: { borderColor: C.green, backgroundColor: 'rgba(16,163,90,0.10)' },
  rateTagT: { fontSize: 12.5, fontWeight: '700', color: C.mute },
  rateTagTOn: { color: C.green },
  rehireRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
  rehireBox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1.5, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  rehireBoxOn: { backgroundColor: C.green, borderColor: C.green },
  rehireTick: { color: '#fff', fontSize: 14, fontWeight: '900', lineHeight: 16 },
  rehireT: { fontSize: 14.5, fontWeight: '700', color: C.ink },
  // peer vouch — the "vouch for your crew" card + roster rows
  vouchCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.indigoSoft, borderRadius: R.lg, paddingHorizontal: 15, paddingVertical: 14, marginTop: 14 },
  vouchCardT: { fontSize: 15, fontWeight: '800', color: C.ink },
  vouchCardSub: { fontSize: 12.5, color: C.mute, fontWeight: '600', marginTop: 2 },
  vouchChevron: { fontSize: 24, color: C.mute2, fontWeight: '300' },
  vouchRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.canvas, borderRadius: R.md, paddingVertical: 11, paddingHorizontal: 12, marginBottom: 8 },
  vouchAv: { width: 36, height: 36, borderRadius: 18, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center' },
  vouchAvT: { color: '#fff', fontSize: 15, fontWeight: '800' },
  vouchName: { flex: 1, fontSize: 15, fontWeight: '700', color: C.ink },
  vouchGo: { fontSize: 13.5, fontWeight: '800', color: C.indigo },
  vouchDone: { fontSize: 13.5, fontWeight: '800', color: C.green },
  revScrim: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
  revBackdrop: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  revSheet: { backgroundColor: C.panel, borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingTop: 8, paddingBottom: 24, paddingHorizontal: 22 },
  revHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: 'rgba(0,0,0,0.14)', alignSelf: 'center', marginBottom: 14 },
  revTitle: { fontSize: 20, fontWeight: '800', color: C.ink, letterSpacing: -0.3 },
  revSub: { fontSize: 13.5, color: C.mute, marginTop: 4, marginBottom: 12 },
  revCard: { backgroundColor: C.canvas, borderRadius: 16, padding: 13, marginBottom: 10 },
  revInfoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  revInfoK: { fontSize: 13, color: C.mute, fontWeight: '600' },
  revInfoV: { fontSize: 14, color: C.ink, fontWeight: '700', flexShrink: 1, marginLeft: 16 },
  revTickets: { marginBottom: 12 },
  revTicketsLabel: { fontSize: 11, color: C.mute, fontWeight: '800', letterSpacing: 0.6, textTransform: 'uppercase', marginBottom: 8 },
  revCrewRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8, borderTopWidth: 1, borderTopColor: C.line },
  revCrewDot: { width: 8, height: 8, borderRadius: 4 },
  revCrewName: { fontSize: 14, fontWeight: '800', color: C.ink },
  revCrewTrade: { fontSize: 12.5, fontWeight: '600', color: C.mute },
  revCrewStatus: { fontSize: 12, color: C.mute, fontWeight: '600', marginTop: 1 },
  revCrewPay: { fontFamily: MONO, fontSize: 13.5, fontWeight: '800', color: C.ink },
  revTicketsNone: { fontSize: 13, color: C.mute, fontStyle: 'italic' },
  revTicketChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  revChip: { backgroundColor: C.green + '18', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  revChipT: { fontSize: 12.5, color: C.green, fontWeight: '700' },
  revAdj: { marginBottom: 12 },
  revAddLink: { fontSize: 14, color: C.indigo, fontWeight: '700', paddingVertical: 4 },
  opMatBtn: { marginTop: 10, backgroundColor: 'rgba(70,54,232,0.08)', borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  opMatT: { color: C.indigo, fontSize: 14, fontWeight: '700' },
  revMatRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 7, borderTopWidth: 1, borderTopColor: 'rgba(0,0,0,0.05)' },
  revMatAmt: { fontSize: 14, fontWeight: '700', color: C.ink },
  revMatNote: { fontSize: 13, fontWeight: '400', color: C.mute },
  revMatMeta: { fontSize: 11.5, color: C.mute, marginTop: 1 },
  revMatOk: { backgroundColor: C.green, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7 },
  revMatOkT: { color: '#fff', fontSize: 12.5, fontWeight: '800' },
  revMatNo: { backgroundColor: 'rgba(0,0,0,0.06)', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7 },
  revMatNoT: { color: C.mute, fontSize: 12.5, fontWeight: '700' },
  revMatTick: { color: C.green, fontSize: 16, fontWeight: '800' },
  revAdjLabel: { fontSize: 12, color: C.mute, fontWeight: '700', marginTop: 10, marginBottom: 8 },
  revTipRow: { flexDirection: 'row', gap: 8 },
  revTipBtn: { flex: 1, backgroundColor: C.canvas, borderRadius: 12, paddingVertical: 12, alignItems: 'center', borderWidth: 1.5, borderColor: 'transparent' },
  revTipBtnOn: { borderColor: C.green, backgroundColor: C.green + '12' },
  revTipBtnT: { fontSize: 14, fontWeight: '800', color: C.ink },
  revTipBtnTOn: { color: C.green },
  revTravelInput: { backgroundColor: C.canvas, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: C.ink, fontWeight: '600' },
  revMoney: { backgroundColor: C.canvas, borderRadius: 16, padding: 13, marginBottom: 8 },
  revMoneyRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 5 },
  revMoneyK: { fontSize: 14, color: C.ink, fontWeight: '700' },
  revMoneyV: { fontSize: 15, color: C.ink, fontWeight: '800' },
  revMoneyKmute: { fontSize: 13, color: C.mute, fontWeight: '600' },
  revMoneyVmute: { fontSize: 13, color: C.mute, fontWeight: '600' },
  revMoneyVnet: { fontSize: 16, color: C.green, fontWeight: '800' },
  revErr: { color: C.red, fontSize: 13, marginTop: 10, textAlign: 'center' },
  revConfirm: { backgroundColor: C.green, borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginTop: 12 },
  revConfirmT: { color: '#fff', fontSize: 15.5, fontWeight: '800' },
  revCancel: { color: C.mute, fontSize: 13.5, textAlign: 'center', fontWeight: '600' },
  arriveScrim: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', paddingHorizontal: 28 },
  arriveCard: { backgroundColor: C.panel, borderRadius: 22, padding: 24 },
  arriveTitle: { fontSize: 19, fontWeight: '800', color: C.ink, letterSpacing: -0.3 },
  arriveSub: { fontSize: 13.5, color: C.mute, marginTop: 8, lineHeight: 19 },
  arriveConfirm: { backgroundColor: C.green, borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 18 },
  arriveConfirmT: { color: '#fff', fontSize: 15, fontWeight: '800' },
  arriveCancel: { color: C.mute, fontSize: 13.5, textAlign: 'center', fontWeight: '600' },
  // Shared canvas that the Welcome + auth form cross-fade on top of (no white flash between them).
  authCanvas: { flex: 1, backgroundColor: C.canvas, alignItems: 'stretch', justifyContent: 'center' },
  // Welcome (choose-your-side) — the first screen. One decision, benefit-framed, generous space.
  wStage: { flex: 1, backgroundColor: C.canvas, paddingHorizontal: 24, paddingTop: 88, paddingBottom: 40, justifyContent: 'space-between' },
  wTop: {},
  wBrandRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 40 },
  wMark: { width: 38, height: 38, borderRadius: 11, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center', ...E.indigo },
  wBrandWord: { fontSize: 19, fontWeight: '800', letterSpacing: -0.3, color: C.ink },
  wHero: { fontSize: 36, fontWeight: '800', letterSpacing: -1, color: C.ink, lineHeight: 40 },
  wSub: { fontSize: 15.5, color: C.mute, lineHeight: 22, marginTop: 12, maxWidth: 330 },
  wProof: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 18, alignSelf: 'flex-start', backgroundColor: C.panel, borderRadius: 999, paddingLeft: 12, paddingRight: 15, paddingVertical: 8, ...E.sm },
  wProofDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.green },
  wProofT: { fontSize: 13, color: C.ink2, fontWeight: '600' },
  wProofNum: { fontWeight: '800', color: C.ink },
  wCards: { gap: 14, marginVertical: 24 },
  wCard: { flexDirection: 'row', alignItems: 'center', gap: 15, backgroundColor: C.panel, borderRadius: R.xl, padding: 18, ...E.md },
  wIconChip: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  wCardBody: { flex: 1 },
  wCardTitle: { fontSize: 17.5, fontWeight: '800', letterSpacing: -0.3, color: C.ink },
  wCardBlurb: { fontSize: 13.5, color: C.mute, lineHeight: 19, marginTop: 4 },
  wCardGo: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  wBottom: { alignItems: 'center', gap: 12 },
  wSignIn: { alignItems: 'center', paddingVertical: 6 },
  wSignInT: { fontSize: 15, color: C.mute, fontWeight: '500' },
  wSignInLink: { color: C.indigo, fontWeight: '800' },
  wTrust: { fontSize: 12, color: C.mute2, fontWeight: '600', textAlign: 'center' },
  // Setup checklist (first-run) — the guided "get ready" landing after signup.
  setStage: { flex: 1, backgroundColor: C.canvas },
  setBrandMark: { width: 52, height: 52, borderRadius: 15, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center', ...E.indigo, marginBottom: 16 },
  setLoadingT: { fontSize: 15, color: C.mute, fontWeight: '600' },
  setScroll: { paddingHorizontal: 24, paddingTop: 76, paddingBottom: 24 },
  setHeader: { marginBottom: 20 },
  setBadge: { width: 56, height: 56, borderRadius: 18, alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  setKicker: { fontSize: 11.5, fontWeight: '800', letterSpacing: 1, color: C.mute, marginBottom: 10 },
  setHero: { fontSize: 30, fontWeight: '800', letterSpacing: -0.8, color: C.ink, lineHeight: 34 },
  setSub: { fontSize: 15, color: C.mute, lineHeight: 21, marginTop: 8, maxWidth: 330 },
  setProgWrap: { marginTop: 20, flexDirection: 'row', alignItems: 'center', gap: 12 },
  setProgTrack: { flex: 1, height: 8, borderRadius: 4, backgroundColor: C.panel2, overflow: 'hidden' },
  setProgFill: { height: 8, borderRadius: 4 },
  setProgT: { fontSize: 12.5, fontWeight: '800', color: C.mute },
  setLive: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.panel, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 11, ...E.sm, marginBottom: 18 },
  setLiveDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.green },
  setLiveT: { fontSize: 13, color: C.ink2, fontWeight: '600' },
  setLiveNum: { fontWeight: '800', color: C.ink },
  setSteps: { gap: 12 },
  setStep: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: C.panel, borderRadius: R.xl, padding: 16, ...E.sm },
  setStepIcon: { width: 34, height: 34, borderRadius: 17, borderWidth: 2, borderColor: C.line, alignItems: 'center', justifyContent: 'center', backgroundColor: C.panel },
  setStepNum: { fontSize: 14, fontWeight: '800', color: C.mute2 },
  setStepTitle: { fontSize: 16, fontWeight: '800', letterSpacing: -0.2, color: C.ink },
  setStepSub: { fontSize: 13, color: C.mute, lineHeight: 18, marginTop: 3 },
  setPill: { backgroundColor: '#FBEFD6', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  setPillT: { fontSize: 11.5, fontWeight: '800', color: C.amber },
  setInline: { backgroundColor: C.panel, borderRadius: R.xl, padding: 16, marginTop: -4 },
  setInput: { backgroundColor: C.canvas, borderColor: C.line, borderWidth: 1, borderRadius: R.md, color: C.ink, fontSize: 16, paddingHorizontal: 14, paddingVertical: 13 },
  setInlineHint: { fontSize: 12, color: C.mute, lineHeight: 17, marginTop: 8 },
  setInlineErr: { fontSize: 13, color: C.red, fontWeight: '600', marginTop: 10 },
  setInlineBtns: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 12 },
  setInlineCancel: { paddingHorizontal: 16, paddingVertical: 11 },
  setInlineCancelT: { fontSize: 14, fontWeight: '700', color: C.mute },
  setInlineSave: { backgroundColor: C.ink, borderRadius: R.md, paddingHorizontal: 20, paddingVertical: 11 },
  setInlineSaveT: { fontSize: 14, fontWeight: '800', color: '#fff' },
  setRecheck: { paddingVertical: 10, paddingLeft: 48 },
  setRecheckT: { fontSize: 13, fontWeight: '700', color: C.indigo },
  setFooter: { paddingHorizontal: 24, paddingBottom: 34, paddingTop: 10 },
  setExplore: { alignItems: 'center', paddingVertical: 10 },
  setExploreT: { fontSize: 14.5, color: C.mute, fontWeight: '500' },
  setExploreLink: { color: C.ink, fontWeight: '800' },
  loginWrap: { flex: 1, backgroundColor: C.canvas, padding: 24, paddingTop: 96 },
  // signup/login — one hero per step, 8pt rhythm, indigo reserved for the primary button
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 32 },
  markSm: { width: 28, height: 28, borderRadius: 8, backgroundColor: C.ink },
  brandWord: { fontSize: 15, fontWeight: '800', letterSpacing: -0.2, color: C.ink },
  loginBack: { alignSelf: 'flex-start', marginBottom: 8 },
  loginBackT: { fontSize: 14, fontWeight: '700', color: C.mute },
  loginHero: { fontSize: 32, fontWeight: '800', letterSpacing: -0.8, color: C.ink },
  loginHelp: { fontSize: 15, color: C.mute, lineHeight: 21, marginTop: 8 },
  loginFields: { marginTop: 32 },
  loginLabel: { marginBottom: 8 },
  loginInput: { backgroundColor: C.panel, borderColor: C.line, borderWidth: 1, borderRadius: R.md, color: C.ink, fontSize: 16, paddingHorizontal: 16, paddingVertical: 16 },
  loginAction: { marginTop: 24 },
  loginMsgErr: { color: C.red, marginTop: 16, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  loginMsgInfo: { color: C.ink2, marginTop: 16, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  loginSwitch: { marginTop: 24, paddingVertical: 8, alignItems: 'center' },
  loginSwitchT: { fontSize: 14, color: C.mute, fontWeight: '500' },
  loginSwitchLink: { color: C.indigo, fontWeight: '800' },
  authToggle: { flexDirection: 'row', backgroundColor: C.panel2, borderRadius: R.md, padding: 4, marginBottom: 22 },
  authTab: { flex: 1, paddingVertical: 10, borderRadius: R.sm || 8, alignItems: 'center' },
  authTabOn: { backgroundColor: C.panel, ...E.sm },
  authTabT: { fontSize: 14, fontWeight: '600', color: C.mute },
  authTabTOn: { color: C.indigo, fontWeight: '800' },
  mark: { width: 42, height: 42, borderRadius: 11, backgroundColor: C.ink, marginBottom: 18 },
  input: { backgroundColor: C.panel, borderColor: C.line, borderWidth: 1, borderRadius: R.md, color: C.ink, fontSize: 16, padding: 15, marginBottom: 4 },
  msg: { color: C.indigo, marginTop: 14, fontSize: 13, lineHeight: 19, fontWeight: '500' },

  // Dark chrome — the top bar is one continuous dark shell with the map and the island tab bar
  // (same #131319 family), so there's no hard white seam where the header meets the map.
  topbar: { flexDirection: 'row', alignItems: 'center', paddingTop: 56, paddingHorizontal: S.xl, paddingBottom: 12, gap: 11, backgroundColor: '#131319' },
  overlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: C.canvas, zIndex: 100 },
  markSm: { width: 34, height: 34, borderRadius: 9, backgroundColor: C.ink, alignItems: 'center', justifyContent: 'center' },
  roleSwitch: { flexDirection: 'row', backgroundColor: 'rgba(255,255,255,0.10)', borderRadius: R.md, padding: 3 },
  roleChip: { paddingVertical: 8, paddingHorizontal: 16, borderRadius: 9, minWidth: 62, alignItems: 'center' },
  roleChipOn: { backgroundColor: C.panel, ...E.sm },
  roleChipT: { color: 'rgba(255,255,255,0.58)', fontWeight: '700', fontSize: 13, letterSpacing: 0.2 },
  roleChipLock: { fontSize: 9 },
  gateScrim: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', paddingHorizontal: 28 },
  gateCard: { backgroundColor: C.panel, borderRadius: 22, padding: 24 },
  gateTitle: { fontSize: 20, fontWeight: '800', color: C.ink, letterSpacing: -0.3 },
  gateSub: { fontSize: 14, color: C.mute, marginTop: 8, lineHeight: 20 },
  gateDevNote: { backgroundColor: 'rgba(91,75,255,0.1)', borderRadius: 12, padding: 12, marginTop: 16 },
  gateDevT: { fontSize: 12, color: C.indigo, fontWeight: '600', lineHeight: 17 },
  gateBtn: { backgroundColor: C.indigo, borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 16 },
  gateBtnT: { color: '#fff', fontSize: 15, fontWeight: '800' },
  gateBtnAlt: { backgroundColor: 'rgba(70,54,232,0.12)', borderRadius: 14, paddingVertical: 15, alignItems: 'center', marginTop: 10 },
  gateBtnAltT: { color: C.indigo, fontSize: 15, fontWeight: '800' },
  gateCancel: { color: C.mute, fontSize: 13.5, textAlign: 'center', fontWeight: '600' },
  gateInputLabel: { fontSize: 12, fontWeight: '800', color: C.mute, letterSpacing: 0.4, textTransform: 'uppercase', marginTop: 16, marginBottom: 7 },
  gateInput: { backgroundColor: C.canvas, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15, color: C.ink, borderWidth: 1, borderColor: C.line },
  gateErr: { color: C.red, fontSize: 12.5, marginTop: 10 },
  gatePendingBadge: { alignSelf: 'flex-start', backgroundColor: 'rgba(214,158,46,0.15)', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 6, marginBottom: 12 },
  gatePendingBadgeT: { color: C.amber, fontSize: 12.5, fontWeight: '800' },
  roleChipTOn: { color: '#fff' },

  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },

  heroCta: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.ink, borderRadius: R.xl, padding: 18, marginBottom: 12 },
  heroCtaTitle: { color: '#fff', fontSize: 16, fontWeight: '700', letterSpacing: -0.2 },
  heroCtaSub: { color: 'rgba(255,255,255,0.55)', fontFamily: MONO, fontSize: 10, marginTop: 3, letterSpacing: 0.5 },
  heroCtaArrow: { color: C.indigo, fontSize: 22, fontWeight: '700', marginLeft: 10 },

  quickRow: { flexDirection: 'row', gap: 9, marginBottom: 20 },
  quickTile: { flex: 1, backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: R.lg, paddingVertical: 18, alignItems: 'center', justifyContent: 'center', minHeight: 84, ...shadowSm },

  card: { backgroundColor: C.panel, borderRadius: R.xl, padding: 18, marginBottom: 11, ...E.sm },
  tag: { fontFamily: MONO, fontSize: 10, fontWeight: '600', letterSpacing: 0.6, textTransform: 'uppercase', color: C.indigo, backgroundColor: C.indigoSoft, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, overflow: 'hidden' },

  live: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.green },

  newBtn: { backgroundColor: C.ink, borderRadius: R.md, padding: 15, alignItems: 'center', marginTop: 12, marginBottom: 6 },
  newBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  filterChip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 7, paddingHorizontal: 13, borderRadius: 999, borderWidth: 1, borderColor: C.line, backgroundColor: '#fff' },
  filterChipOn: { backgroundColor: C.ink, borderColor: C.ink },
  filterT: { fontSize: 13, fontWeight: '600', color: C.mute },
  filterTOn: { color: '#fff' },
  filterN: { fontSize: 11, fontWeight: '700', color: C.mute2, fontFamily: MONO },
  filterNOn: { color: 'rgba(255,255,255,0.7)' },
  progTrack: { height: 5, borderRadius: 3, backgroundColor: C.line2, marginTop: 10, overflow: 'hidden' },
  progFill: { height: 5, borderRadius: 3, backgroundColor: C.green },
  detailItem: { backgroundColor: C.canvas, borderRadius: R.md, borderWidth: 1, borderColor: C.line, padding: 12, marginBottom: 8 },

  steps: { flexDirection: 'row', gap: 6, marginBottom: 18 },
  askBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: C.ink, borderRadius: R.lg, paddingVertical: 20, paddingHorizontal: 20, marginBottom: 20, ...E.md },
  askBtnT: { color: '#fff', fontFamily: MONO, fontSize: 17, fontWeight: '800', letterSpacing: 0.2 },
  askBtnPlus: { width: 34, height: 34, borderRadius: 17, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center' },
  askBtnPlusT: { color: '#fff', fontSize: 20, fontWeight: '700', lineHeight: 24 },
  // docked request bar — joins the map's bottom edge as one card
  askDock: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: C.ink, marginHorizontal: 20,
    borderBottomLeftRadius: 20, borderBottomRightRadius: 20,
    borderWidth: 2, borderTopWidth: 0, borderColor: '#16161A',
    paddingVertical: 16, paddingHorizontal: 18, ...E.md },
  askDockLabel: { color: 'rgba(255,255,255,0.5)', fontSize: 10.5, fontWeight: '700', letterSpacing: 1.2, marginBottom: 3 },
  askDockStandalone: { marginTop: 16, borderTopWidth: 2, borderTopLeftRadius: 20, borderTopRightRadius: 20 },
  askDockT: { color: '#fff', fontSize: 17, fontWeight: '700', letterSpacing: -0.3 },
  askDockPlus: { width: 40, height: 40, borderRadius: 20, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center', ...E.sm },
  askDockPlusT: { color: '#fff', fontSize: 22, fontWeight: '600', lineHeight: 26, marginTop: -1 },
  // client home: the post CTA is the hero when idle (enlarged), and recedes to a quiet
  // neutral bar when a job is waiting to be paid — so only ONE loud element shows at a time.
  askDockTLg: { fontSize: 21, letterSpacing: -0.4 },
  askDockQuiet: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line },
  askDockLabelQuiet: { color: C.mute2 },
  askDockTQuiet: { color: C.ink, fontSize: 16, fontWeight: '700' },
  askDockPlusQuiet: { backgroundColor: C.indigoSoft },
  askDockPlusTQuiet: { color: C.indigo },
  homeEmptyHero: { fontSize: 30, fontWeight: '800', letterSpacing: -0.7, color: C.ink, marginTop: 8 },
  homeEmptySub: { fontSize: 15, color: C.mute, lineHeight: 22, marginTop: 8 },
  needsCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.indigo, borderRadius: R.lg, padding: 16, marginBottom: 10, ...E.indigo },
  needsSuburb: { color: '#fff', fontSize: 17, fontWeight: '800', letterSpacing: 0.2 },
  needsSummary: { color: 'rgba(255,255,255,0.82)', fontSize: 12.5, marginTop: 2 },
  needsStatus: { color: 'rgba(255,255,255,0.92)', fontFamily: MONO, fontSize: 10.5, marginTop: 8, letterSpacing: 0.2 },
  needsCta: { backgroundColor: '#fff', borderRadius: R.md, paddingVertical: 10, paddingHorizontal: 14 },
  needsCtaT: { color: C.indigo, fontFamily: MONO, fontSize: 12.5, fontWeight: '800' },
  composeItem: { backgroundColor: C.panel, borderRadius: R.md, padding: 14, borderWidth: 1, borderColor: C.line, marginBottom: 10 },
  composeIcon: { width: 38, height: 38, borderRadius: 10, backgroundColor: 'rgba(61,43,255,0.08)', alignItems: 'center', justifyContent: 'center' },
  rateInline: { flexDirection: 'row', alignItems: 'center', marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.line },
  rateStep: { width: 30, height: 30, borderRadius: 8, backgroundColor: C.canvas, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  rateStepT: { fontSize: 17, color: C.ink, fontWeight: '600', lineHeight: 20 },
  rateInlineVal: { fontFamily: MONO, fontSize: 14, fontWeight: '800', color: C.ink, minWidth: 78, textAlign: 'center' },
  composeAdd: { borderWidth: 1.5, borderColor: C.indigo, borderStyle: 'dashed', borderRadius: R.md, paddingVertical: 15, alignItems: 'center' },
  composeAddT: { fontFamily: MONO, fontSize: 13, fontWeight: '700', color: C.indigo, letterSpacing: 0.2 },
  composeEst: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 20, paddingTop: 14, borderTopWidth: 1, borderTopColor: C.line },
  composeFooter: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: S.xl, paddingTop: 12, backgroundColor: C.canvas, borderTopWidth: 1, borderTopColor: C.line },
  stepBar: { flex: 1, height: 4, borderRadius: 2, backgroundColor: C.line },
  stepBarOn: { backgroundColor: C.indigo },
  wizHead: { marginBottom: 12 },
  back: { color: C.indigo, fontSize: 14, fontWeight: '600' },

  itemRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: C.panel, borderColor: C.line, borderWidth: 1, borderRadius: R.lg, padding: 12, marginBottom: 9, gap: 11 },
  qty: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: C.line, borderRadius: R.sm, overflow: 'hidden' },
  qtyBtn: { color: C.indigo, fontSize: 17, fontWeight: '800', paddingHorizontal: 12, paddingVertical: 6 },
  qtyVal: { color: C.ink, fontWeight: '800', minWidth: 22, textAlign: 'center', fontFamily: MONO },
  rm: { color: C.mute2, fontSize: 14, paddingHorizontal: 4 },
  addrList: { marginTop: 6, borderWidth: 1, borderColor: C.line, borderRadius: R.md, backgroundColor: C.panel, overflow: 'hidden' },
  addrRow: { paddingHorizontal: 13, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: C.line },
  reqCard: { backgroundColor: C.panel, borderRadius: R.lg, marginBottom: 10, overflow: 'hidden', ...E.sm },
  reqCardOpen: { borderColor: 'rgba(61,43,255,0.25)' },
  reqHead: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 14, paddingVertical: 13 },
  reqBody: { paddingHorizontal: 14, paddingBottom: 14 },
  urgentDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.amber },
  miniCard: { backgroundColor: C.panel, borderRadius: R.lg, padding: 15, marginBottom: 10, ...E.sm },
  pill: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 999 },
  pillT: { fontSize: 11, fontWeight: '700', letterSpacing: 0.1 },
  passBtn: { alignItems: 'center', paddingVertical: 11, marginTop: 6 },
  passBtnT: { fontSize: 14, fontWeight: '600', color: C.mute },
  matchCard: { backgroundColor: C.panel, borderRadius: R.xl, padding: 18, marginBottom: 18, ...E.md },
  matchAvatar: { width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center' },
  matchAvatarT: { color: '#fff', fontSize: 22, fontWeight: '800' },
  matchHead: { fontSize: 16.5, fontWeight: '800', color: C.ink, letterSpacing: -0.3 },
  matchSub: { fontSize: 13, color: C.ink2, marginTop: 2 },
  matchMeta: { fontSize: 12, color: C.mute, marginTop: 3 },
  matchMsgBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: R.md, paddingVertical: 13, marginTop: 15 },
  matchMsgT: { color: '#fff', fontWeight: '800', fontSize: 14.5, letterSpacing: 0.1 },
  matchDetailRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 14, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.line },
  matchDetailT: { flex: 1, fontSize: 13, color: C.mute, fontWeight: '600' },
  matchDetailChevron: { fontSize: 13, color: C.indigo, fontWeight: '700', marginLeft: 8 },
  matchBadge: { backgroundColor: '#fff', borderRadius: 999, minWidth: 20, height: 20, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 },
  matchBadgeT: { color: C.indigo, fontSize: 11, fontWeight: '800' },
  crewBar: { height: 6, borderRadius: 3, backgroundColor: C.panel2, marginTop: 12, overflow: 'hidden' },
  crewBarFill: { height: 6, borderRadius: 3 },
  crewRow: { flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: C.panel2, borderRadius: R.md, paddingVertical: 10, paddingHorizontal: 12 },
  crewDot: { width: 8, height: 8, borderRadius: 4 },
  crewName: { fontSize: 14, fontWeight: '700', color: C.ink },
  crewStatus: { fontSize: 12, color: C.mute, marginTop: 1 },
  crewMsg: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: 999, paddingVertical: 7, paddingHorizontal: 13 },
  crewMsgT: { fontSize: 12.5, fontWeight: '700', color: C.indigo },
  crewBadge: { backgroundColor: C.indigo, borderRadius: 999, minWidth: 18, height: 18, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 5 },
  crewBadgeT: { color: '#fff', fontSize: 10, fontWeight: '800' },
  crewWaiting: { fontSize: 12.5, color: C.mute, fontStyle: 'italic', paddingVertical: 4, paddingLeft: 2 },
  opMsgBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderWidth: 1.5, borderColor: C.indigo, borderRadius: R.md, paddingVertical: 11, marginTop: 12 },
  opMsgT: { color: C.indigo, fontWeight: '700', fontSize: 14 },
  nameInput: { flex: 1, height: Z.fieldH50 - 6, backgroundColor: C.panel2, borderRadius: R.md, paddingHorizontal: 14, fontSize: 14.5, color: C.ink },
  nameSave: { backgroundColor: C.ink, borderRadius: R.md, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center' },
  nameSaveT: { color: '#fff', fontWeight: '700', fontSize: 14 },
  viewProfileBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 14, paddingTop: 14, borderTopWidth: 1, borderTopColor: C.line },
  viewProfileT: { color: C.indigo, fontSize: 14, fontWeight: '800' },
  adminCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.ink, borderRadius: R.lg, padding: 14, marginTop: 18 },
  adminIcon: { width: 38, height: 38, borderRadius: 10, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center' },
  adminTitle: { color: '#fff', fontSize: 15.5, fontWeight: '800' },
  adminSub: { color: '#fff', opacity: 0.6, fontSize: 12, marginTop: 2, fontWeight: '600' },
  adminChev: { color: '#fff', opacity: 0.5, fontSize: 22, fontWeight: '300' },
  emptyWrap: { alignItems: 'center', paddingVertical: 22, paddingHorizontal: 24 },
  emptyIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: C.panel2, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: C.ink, letterSpacing: -0.2, textAlign: 'center' },
  emptySub: { fontSize: 13.5, color: C.mute, marginTop: 5, textAlign: 'center', lineHeight: 19, maxWidth: 260 },
  emptyCta: { backgroundColor: C.ink, borderRadius: R.md, paddingVertical: 12, paddingHorizontal: 22, marginTop: 16 },
  emptyCtaT: { color: '#fff', fontWeight: '700', fontSize: 14 },
  actDetail: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.line2 },
  actRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4, gap: 12 },
  actLabel: { fontSize: 13, color: C.mute },
  actVal: { fontSize: 13, color: C.ink, fontWeight: '600' },
  actTotal: { borderTopWidth: 1, borderTopColor: C.line2, marginTop: 6, paddingTop: 10 },
  stallBanner: { backgroundColor: C.amberSoft, borderRadius: R.lg, padding: 15, marginBottom: 14 },
  stallTitle: { fontSize: 15, fontWeight: '800', color: C.amber, letterSpacing: -0.2 },
  stallSub: { fontSize: 13, color: C.ink2, lineHeight: 18, marginTop: 4 },
  stallBtn: { backgroundColor: C.amber, borderRadius: R.md, paddingVertical: 12, alignItems: 'center', marginTop: 12 },
  stallBtnT: { color: '#fff', fontWeight: '800', fontSize: 14, letterSpacing: 0.2 },
  repostBtn: { backgroundColor: C.ink, borderRadius: R.md, paddingVertical: 13, alignItems: 'center' },
  repostBtnT: { color: '#fff', fontFamily: MONO, fontSize: 13, fontWeight: '700', letterSpacing: 0.3 },
  doneWrap: { alignItems: 'center', paddingVertical: 20, paddingHorizontal: 12, backgroundColor: 'rgba(34,168,108,0.06)', borderRadius: R.md, marginBottom: 4 },
  doneCheck: { width: 44, height: 44, borderRadius: 22, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  doneCheckT: { color: '#fff', fontSize: 22, fontWeight: '800', lineHeight: 26 },
  doneTitle: { fontFamily: MONO, fontSize: 15, fontWeight: '800', color: C.ink, letterSpacing: 0.2 },
  doneSub: { fontSize: 12, color: C.mute, marginTop: 4, textAlign: 'center' },
  opCard: { backgroundColor: C.canvas, borderRadius: R.md, padding: 12, marginTop: 8, marginBottom: 2, borderWidth: 1, borderColor: C.line2 },
  opAvatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: C.indigo, alignItems: 'center', justifyContent: 'center', marginRight: 11 },
  opAvatarT: { color: '#fff', fontFamily: MONO, fontSize: 16, fontWeight: '800' },
  opCapRow: { flexDirection: 'row', marginTop: 9 },
  opCapChip: { fontFamily: MONO, fontSize: 10, fontWeight: '700', color: C.green, backgroundColor: 'rgba(34,168,108,0.10)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: R.sm, overflow: 'hidden' },
  progThin: { height: 3, backgroundColor: C.line2 },
  progThinFill: { height: 3, backgroundColor: C.green },
  slider: { height: 40, justifyContent: 'center', marginTop: 14, marginBottom: 2 },
  sliderTrack: { position: 'absolute', left: 0, right: 0, height: 6, borderRadius: 3, backgroundColor: C.line2 },
  sliderRange: { position: 'absolute', height: 6, borderRadius: 3, backgroundColor: 'rgba(0,135,90,0.18)' },
  sliderFloorMark: { position: 'absolute', width: 2, height: 14, backgroundColor: C.mute2, marginLeft: -1 },
  sliderKnob: { position: 'absolute', width: 26, height: 26, borderRadius: 13, backgroundColor: C.indigo, marginLeft: -13, borderWidth: 3, borderColor: '#fff', ...shadowSm },
  presetRow: { flexDirection: 'row', gap: 8 },
  preset: { flex: 1, paddingVertical: 12, borderRadius: R.sm, borderWidth: 1, borderColor: C.line, alignItems: 'center', backgroundColor: C.panel },
  presetOn: { borderColor: C.indigo, backgroundColor: C.indigoSoft },
  presetT: { fontFamily: MONO, fontSize: 14, fontWeight: '700', color: C.mute },
  presetTOn: { color: C.indigo },
  dangerBtn: { backgroundColor: 'rgba(200,60,50,0.10)', borderWidth: 1, borderColor: 'rgba(200,60,50,0.35)', borderRadius: R.md, paddingVertical: 13, alignItems: 'center' },
  dangerBtnT: { color: C.red, fontWeight: '700', fontSize: 14 },
  ghostBtn: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: R.md, paddingVertical: 13, alignItems: 'center' },
  ghostBtnT: { color: C.mute, fontWeight: '600', fontSize: 14 },
  track: { marginTop: 8, marginBottom: 4 },
  trackRow: { flexDirection: 'row', alignItems: 'flex-start' },
  trackStep: { flex: 1, alignItems: 'center' },
  trackLineWrap: { flexDirection: 'row', alignItems: 'center', width: '100%', justifyContent: 'center' },
  trackLine: { flex: 1, height: 2, backgroundColor: C.line },
  trackLineOn: { backgroundColor: C.green },
  dot: { width: 18, height: 18, borderRadius: 9, backgroundColor: C.panel, borderWidth: 2, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  dotOn: { borderColor: C.green, backgroundColor: C.green },
  dotNow: { borderColor: C.indigo, backgroundColor: C.panel },
  dotTick: { color: '#fff', fontSize: 10, fontWeight: '700', lineHeight: 12 },
  trackLabel: { fontSize: 9.5, color: C.mute2, marginTop: 5, textAlign: 'center' },
  addRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
  addBtn: { flex: 1, paddingVertical: 13, borderRadius: R.md, borderWidth: 1.5, borderColor: C.line, borderStyle: 'dashed', alignItems: 'center' },
  picker: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: R.md, paddingVertical: 10, paddingHorizontal: 13 },

  seg: { flexDirection: 'row', backgroundColor: C.line2, borderRadius: R.md, padding: 3 },
  segBtn: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 8 },
  segBtnOn: { backgroundColor: C.panel, ...shadowSm },
  segT: { color: C.mute, fontWeight: '600', fontSize: 13 },
  segTOn: { color: C.ink },

  reviewRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 7 },
  divide: { height: 1, backgroundColor: C.line, marginVertical: 8 },

  rateTrack: { height: 40, backgroundColor: C.line2, borderRadius: R.sm, marginTop: 18, marginBottom: 6, position: 'relative' },
  rateRange: { position: 'absolute', top: 8, bottom: 8, backgroundColor: C.greenSoft, borderWidth: 1, borderColor: 'rgba(0,135,90,0.4)', borderRadius: 5 },
  rateFloor: { position: 'absolute', top: -4, bottom: -4, width: 2, backgroundColor: C.mute2 },
  rateYou: { position: 'absolute', top: -6, bottom: -6, width: 3, backgroundColor: C.indigo, borderRadius: 2 },
  rateBtns: { flexDirection: 'row', gap: 8, marginTop: 12 },
  rateBtn: { flex: 1, backgroundColor: C.panel2, borderWidth: 1, borderColor: C.line, borderRadius: R.sm, paddingVertical: 10, alignItems: 'center' },
  rateBtnT: { color: C.ink, fontWeight: '700', fontFamily: MONO, fontSize: 13 },

  settle: { backgroundColor: C.panel2, borderColor: C.line, borderTopWidth: 1, padding: 14, marginHorizontal: -16, marginBottom: -16, marginTop: 14 },

  onlineRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: C.panel, borderColor: C.line, borderWidth: 1, borderRadius: R.lg, padding: 16, ...shadow },
  sw: { width: 52, height: 30, borderRadius: 18, backgroundColor: '#D8D8D4', justifyContent: 'center', padding: 3 },
  swOn: { backgroundColor: C.green },
  swKnob: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#fff', ...shadowSm },
  swKnobOn: { alignSelf: 'flex-end' },

  capWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  capChip: { backgroundColor: C.indigoSoft, borderWidth: 1, borderColor: 'rgba(61,43,255,0.25)', borderRadius: R.sm, paddingVertical: 8, paddingHorizontal: 12 },
  capRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.panel, borderRadius: R.lg, paddingHorizontal: 14, paddingVertical: 13, marginBottom: 8, ...E.sm },
  readyPill: { backgroundColor: 'rgba(16,163,90,0.12)', paddingHorizontal: 9, paddingVertical: 4, borderRadius: 6 },
  readyText: { color: C.green, fontSize: 10.5, fontWeight: '700', fontFamily: MONO, letterSpacing: 0.3 },
  notReadyPill: { backgroundColor: 'rgba(217,144,10,0.14)', paddingHorizontal: 9, paddingVertical: 4, borderRadius: 6 },
  notReadyText: { color: C.amber, fontSize: 10.5, fontWeight: '700', fontFamily: MONO, letterSpacing: 0.3 },
  capAddRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  miniBtn: { backgroundColor: C.panel, borderWidth: 1, borderColor: C.line, borderRadius: R.sm, paddingVertical: 8, paddingHorizontal: 12 },
  // Collapsed "What I supply" — a calm one-line summary that opens the full editor.
  capSummary: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.panel, borderRadius: R.lg, paddingHorizontal: 14, paddingVertical: 13, marginTop: 10, ...E.sm },
  capTagWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  capTag: { backgroundColor: 'rgba(16,163,90,0.12)', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  capTagT: { color: C.green, fontSize: 11.5, fontWeight: '700' },
  capTagMuted: { backgroundColor: C.panel2, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  capTagMutedT: { color: C.mute, fontSize: 11.5, fontWeight: '700' },
  capChevron: { fontSize: 26, color: C.mute2, fontWeight: '300', marginTop: -2 },

  jobCard: { backgroundColor: C.panel, borderRadius: R.xl, padding: 18, paddingLeft: 20, marginTop: 11, borderLeftWidth: 3, borderLeftColor: C.indigo, ...E.md },
  bioBox: { marginTop: 10, backgroundColor: C.panel2, borderRadius: R.md, padding: 11 },
  bioText: { fontSize: 13, lineHeight: 19, color: C.ink2 || C.ink },

  briefBox: { marginTop: 12, backgroundColor: C.panel2, borderRadius: R.md, padding: 13, gap: 9 },
  briefRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  briefK: { fontSize: 11, fontWeight: '700', color: C.mute, letterSpacing: 0.4, textTransform: 'uppercase', width: 68 },
  briefV: { fontSize: 13.5, color: C.ink, flex: 1, lineHeight: 19 },
  briefBio: { fontSize: 13.5, lineHeight: 20, color: C.ink, marginTop: 3 },
  briefMore: { fontSize: 12, fontWeight: '700', color: C.indigo, marginTop: 5 },
  bioMore: { fontSize: 12, fontWeight: '700', color: C.indigo, marginTop: 5 },
  paidRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  opPaidWrap: { backgroundColor: 'rgba(0,135,90,0.08)', borderRadius: R.md, padding: 12, borderWidth: 1, borderColor: 'rgba(0,135,90,0.25)' },
  opPaidCheck: { width: 24, height: 24, borderRadius: 12, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center' },
  opPaidCheckT: { color: '#fff', fontSize: 13, fontWeight: '800', lineHeight: 16 },
  opAwaitWrap: { backgroundColor: 'rgba(214,158,46,0.08)', borderRadius: R.md, padding: 12, borderWidth: 1, borderColor: 'rgba(214,158,46,0.22)' },
  successBanner: { backgroundColor: C.greenSoft, borderWidth: 1, borderColor: 'rgba(0,135,90,0.3)', borderRadius: R.md, padding: 14, marginTop: 12 },
  successText: { color: C.green, fontWeight: '700', fontSize: 14 },
  pips: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, gap: 5 },
  payRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: C.line },
  payBig: { fontFamily: MONO, fontSize: 26, fontWeight: '800', color: C.ink, letterSpacing: -0.5 },
  payUnit: { fontFamily: MONO, fontSize: 14, fontWeight: '700', color: C.mute },
  payEst: { fontSize: 12, color: C.mute, fontWeight: '600', marginTop: 2 },
  payDur: { alignItems: 'flex-end' },
  payDurT: { fontSize: 15, fontWeight: '800', color: C.ink },
  payDurL: { fontSize: 10, color: C.mute2, fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase' },
  pip: { width: 22, height: 6, borderRadius: 3, backgroundColor: C.line2 },
  pipFilled: { backgroundColor: C.green },

  avatar: { width: 50, height: 50, borderRadius: 14, backgroundColor: C.line2, alignItems: 'center', justifyContent: 'center' },
  acctRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14, gap: 10 },
  signoutBtn: { marginTop: 20, borderWidth: 1, borderColor: C.line, borderRadius: R.md, padding: 15, alignItems: 'center' },
  signoutText: { color: C.red, fontWeight: '600', fontSize: 15 },
  csScrim: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
  csSheet: { backgroundColor: C.panel, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, paddingBottom: 34, alignItems: 'center' },
  csGrip: { width: 40, height: 4, borderRadius: 2, backgroundColor: C.line, marginBottom: 18 },
  csIcon: { width: 52, height: 52, borderRadius: 26, backgroundColor: C.indigoSoft || 'rgba(61,43,255,0.08)', alignItems: 'center', justifyContent: 'center', marginBottom: 14 },
  csTitle: { fontSize: 19, fontWeight: '800', color: C.ink, marginBottom: 8 },
  csBody: { fontSize: 14, lineHeight: 21, color: C.mute, textAlign: 'center', marginBottom: 22 },
  csBtn: { backgroundColor: C.indigo, borderRadius: R.md, paddingVertical: 14, paddingHorizontal: 40, alignSelf: 'stretch', alignItems: 'center' },
  csBtnT: { color: '#fff', fontWeight: '700', fontSize: 15 },

  primary: { backgroundColor: C.indigo, borderRadius: R.md, padding: 16, alignItems: 'center', shadowColor: C.indigo, shadowOpacity: 0.24, shadowRadius: 10, shadowOffset: { width: 0, height: 2 } },
  primaryOff: { opacity: 0.35, shadowOpacity: 0 },
  primaryT: { color: '#fff', fontWeight: '600', fontSize: 15, letterSpacing: -0.1 },
});
